qcore/tests/test_caching.py

.keys() returns a special view, not a list, in Python 3.
There is an additional test failure in test_decorators.py that I'm not
sure yet how to fix; it's not obvious how to create an equality check
that works across Cythonized and non-Cythonized Python 2 and 3.

Fix test_caching.py test failures under Python 3

---

qcore/decorators.py

This code (hacky though it is) works in Python 2 and 3, with and without
Cython. All tests pass in Python 3 now.

qcore: fix DecoratorBinder equality

---

qcore/decorators.py
qcore/helpers.pxd
qcore/helpers.py
qcore/tests/test_helpers.py

Ran into this while migrating some code using MarkerObjects to Python 3. The
name of the MarkerObject is supposed to be a human-readable label, so it
should be text, not bytes.
This change enforces that the name is str (i.e., text) in Python 3. In Python 2,
we allow both but issue a warning when using str (i.e., bytes in Python 3).
Passes tests in Python 2.7 and 3.5 on OS X.

MarkerObject: name should be text, not bytes

---

qcore/helpers.py

We have a test that passing a bytes name to a MarkerObject throws a TypeError, but without Cython there is nothing to enforce that.

make test_helpers work without Cython

---

qcore/caching.py

As @ymichael noticed, @memoize is inefficient because it ends up calling inspect.getargspec every time the memoized function is called. This patch uses get_args_tuple instead, which should be more efficient.

optimize memoize

---

qcore/enum.py
qcore/tests/test_enum.py

This makes it easier to use core.Enum in places where serialization is required. The
name parallels the Python 3 standard library enum module.

enum: add IntEnum

---

qcore/caching.py
qcore/decorators.py
qcore/enum.py

Otherwise, cython is a run-time dependency when
qcore is run as pure Python.
Also fix MarkerObjects to use unicode names in
Python 2, because using str now produces a
warning.

qcore: fix pure-python import

---

qcore/enum.py

Enum names are text, so they should be unicode.

enum: make names unicode

---

qcore/enum.py
qcore/tests/test_enum.py

- Allow longs as enum values in Python 2.
- Ensure members are returned in order of their values in
get_names() and get_members().
- Make enum values singletons instead of creating new ones
in e.g. .parse().
- Make instantiating an enum equivalent to calling .parse()
on it.
- As a consequence, disallow instantiating an enum with an
invalid value.
The last few changes were more invasive than I'd hoped, and
required a few behavior changes in the tests. I don't think
this will affect real use cases.

enum: various changes

---

qcore/disallow_inheritance.py
qcore/helpers.py
qcore/tests/test_disallow_inheritance.py
qcore/tests/test_helpers.py

Seems to be some bad interaction with Cython.

qcore: make DisallowInheritance work with six.with_metaclass

---

qcore/enum.py
qcore/tests/test_enum.py

Some of the new tests fail in Python 2 (but not Python 3) without this change.

enums: fix KeyError with unicode value in Python 2

---

README.rst

We didn't actually put this in the open-source version of qcore.

remove p64 from README

---

qcore/caching.py
qcore/inspection.py
qcore/tests/test_caching.py
qcore/tests/test_inspection.py

- test support of annotations by qcore.inspection.getargspec
- disallow keyword-only arguments, which previously were allowed but weren't
handled correctly
- add tests for getargspec() on methods
- use inspection.getargspec for all caching functions, so that functions with
annotations are supported, and add tests for this behavior
I'm rejecting functions with keyword-only arguments because there is no way to express their semantics without changing the return value of `getargspec()`, which assumes that defaults apply to the last names in the argument list. That assumption doesn't hold for functions like:
```
def f(x=3, *, y): ...
```
Python 3's `inspect` module gets around this by adding the `getfullargspec` function, which adds additional fields for keyword-only arguments and …

getargspec: improved handling of Python 3 functions

---

qcore/caching.py
qcore/inspection.py
qcore/tests/test_caching.py
requirements.txt
setup.py

This paves the way towards fixing quora/asynq#32.
There's a minor bug here: given a function
@memoize
def f(x, *, y): pass
if you first call
f(1, y=2)
to warm the cache and then call
f(1, 2)
you won't get the error you should get because y is keyword-only. I don't think that's
a major problem.

add support for keyword-only args in qcore.caching

---

qcore/enum.py
qcore/tests/test_enum.py

Without this change, enum objects pickled in Python 3 cannot be
unpickled in Python 2.

fix unpickling of enums pickled in Python 3

---

qcore/enum.py

This won't achieve perfect 2/3 interoperability for Python 3.3, but I don't see much of a current need for that.

enum: attempt to fix 3.3 build

---

setup.py

This should help me to allow setup.py scripts to use Cython in them in theory.

qcore: add Cython as a requires

---

qcore/decorators.py
qcore/tests/test_decorators.py

The current implementation doesn't work with pickle due to a bug (or at least, odd design choice) of Cython: it always tries to pickle using the original name of the function, rather than the __name__ attribute. This is wrong for the qcore.retry, which uses a function called "retry_fun" to wrap the original function. I found that we can work around this by manually setting __reduce__ on the function object.

fix pickling @retry functions

---

qcore/enum.py
setup.py

This makes qcore enums pickle in the same way as enum.Enum, which
should make it easier to change away from qcore.Enum to enum.Enum.
Because this only changes dumps(), not loads(), there should be no
backward compatibility issue with pickles generated from previous
versions of qcore.

qcore: change pickle reduce implementation

---

qcore/decorators.pyi

It is intended to take a context manager class, not a context manager instance.

fix stub for `decorator_of_context_manager`

---

.travis.yml
setup.py
travis/build-wheels.sh

This updates the Travis config to build and test using manylinux wheels, similar to this PR for asynq: https://github.com/quora/asynq/pull/67
Two noteworthy changes from that asynq change:
- The addition of python3.7 support (since 3.7 was not out at the time of the asynq PR). The version of 3.7 in the manylinux Docker image is the final 3.7.0 release.
- Running the `mypy` command within the bash script. `tox` doesn't pick up on the python3.6 version available under `/opt/python/cp36-cp36m`, so I had to manually check for the python version and run `mypy` in the Travis script instead.

Build wheels in Travis

---

.gitignore
qcore/disallow_inheritance.py
qcore/enum.py
qcore/events.py

Classes passed to `six.with_metaclass()` are expected to have a
`__prepare__` method to pass `tox` checks, which is not defined by
default in PY2 and not used.
See also <https://github.com/benjaminp/six/issues/252>.

qcore: Add __prepare__ to some meta classes

---

qcore/microtime.py
qcore/microtime.pyi
setup.py
travis/build-wheels.sh

We already use the Utime newtype internally, but we need to teach the typechecker that utime() returns a Utime.

expose Utime newtype

---

CHANGELOG
setup.py

We need to bump up the version significantly because we accidentally used a far too high version internally.

prepare release 1.5.0

---

qcore/asserts.py
qcore/asserts.pyi
qcore/tests/test_asserts.py

Add `assrt_startswith()` and `assert_endswith()` checks for strings, to
make such tests easier, as alternate solutions to such checks either
require setting the needle in a local variable, or writing a boolean
assertion for result of `str.startswith()`/`str.endswith()`, which hide
the actual and expected values.
Test Plan:
Added unit tests.

asserts: Add startswith()/endswith() checks for strings

---

qcore/asserts.pyi

expected_exception_found is important because it's expected to be accessed in code.

add attributes to AssertRaises stub

---

qcore/testing.py

These are fairly slow to import and make importing qcore itself slow. For TEST_PREFIX, we can just use it directly—it's not going to change. SkipTest we can import only when it's needed, so we don't always have to import nose.

Remove slow imports in testing.py

---

qcore/decorators.pxd
qcore/decorators.py
qcore/decorators.pyi

decorators: add __self__

---

qcore/asserts.py
qcore/tests/test_asserts.py

Without enforcing `ascii` representation, strings with any uncommon
Unicode characters can be hard to debug and fix.

asserts: Use `ascii` representation of values in exception message

---

CHANGELOG
qcore/inspection.py

The cache is broken for classes: if we set the cache on a base class
and then try to get the full name of a child class, it will use the
base's value. We could fix this by checking only __dict__, but it seems
better to just avoid the cache. Callers should add caching if performance
is critical.

qcore.inspection: Remove cache from get_full_name

---

setup.py

the latest version of Cython (3.0.0) has backwards incompatible changes that prevents qcore from building properly now

pin Cython when building qcore

---

pyproject.toml
qcore/testing.py
qcore/tests/test_testing.py

nose does not work for recent Python versions anymore. unittest.SkipTest is available for >=2.7 which is enough for supported versions.

remove nose usage from testing.disabled
